attributes:
  metadata:
    restrictions:
        - condition: "settings:lma_collector.influxdb_mode.value == 'disabled' and settings:lma_collector.elasticsearch_mode.value == 'disabled'"
        action: "disable"
        message: "Please enable Metrics and/or Events analytic in LMA Collector plugin to enable Nagios Alerting system"

  node_name:
    value: 'nagios'
    label: "Alerting node name"
    description: 'Label of the node running the Nagios Infrastructure Alerting plugin that is deployed in the environment.'
    weight: 30
    type: "text"

  nagios_user:
    value: 'nagiosadmin'
    label: 'Nagios HTTP user'
    description: 'The user to access Nagios Web Interface'
    weight: 41
    type: "text"
    regex: &not_empty_parameter
      source: '\S'
      error: "Invalid value"

  nagios_password:
    value: 'r00tme'
    label: 'Nagios HTTP password'
    description: 'The password to access Nagios Web Interface'
    weight: 42
    type: "password"
    regex: *not_empty_parameter

  email_all_notification:
    value: ''
    label: 'Email addresse'
    description: 'The recipient receiving all alert notifications'
    weight: 45
    type: "text"
    regex: &email_address_regex
      source: '[a-z0-9!#$%&*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.?)?[a-z0-9]?(?:[a-z0-9-]*[a-z0-9])?'
      error: "Invalid Email"

  alias_all_notification:
    value: 'Admin'
    label: 'Name'
    description: 'The recipient name receiving all alert notifications'
    weight: 50
    type: "text"
    regex: *not_empty_parameter

  enable_recipient_for_critical:
    type: "checkbox"
    weight: 55
    value: false
    label: "Configure one recipient receiving only critical alert notifications"

  email_critical_notification:
    value: ''
    label: 'Email addresse'
    description: 'The recipient receiving only critical alert notifications'
    weight: 60
    type: "text"
    #restrictions:
        #- condition: "settings:lma_infrastructure_alerting.enable_recipient_for_critical.value != true or settings:lma_infrastructure_alerting.nagios_mode.value != 'local'"
        #  action: "disable"
    regex: *email_address_regex

  alias_critical_notification:
    value: 'SuperHero'
    label: 'Name'
    description: 'The recipient name receiving only critical alert notifications'
    weight: 65
    type: "text"
    regex: *not_empty_parameter
    #restrictions:
    #    - condition: "settings:lma_infrastructure_alerting.enable_recipient_for_critical.value != true or settings:lma_infrastructure_alerting.nagios_mode.value != 'local'"
    #      action: "disable"
